package yeti.test;

import yeti.annotations.YetiTrace;


/** Class automatically generated by YETI **/
public class TGenString {

   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_1() throws Exception {
      java.lang.String v672=new java.lang.String((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764459
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.<init>(String.java:147)
      YETI EXCEPTION - END**/ 
      /** original locs: 1427 minimal locs: 1**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_2() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      int v11=3; // time:1316010763667
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      int v40=-2147483647; // time:1316010763713
      v39.getChars((int)v11,(int)v11,(char[])v2,(int)v40);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763714
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 3
      	at java.lang.String.getChars(String.java:849)
      YETI EXCEPTION - END**/ 
      /** original locs: 91 minimal locs: 10**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_3() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      char[] v59=v39.toCharArray(); // time:1316010763725
      int v248=3; // time:1316010763992
      int v335=-2147483648; // time:1316010764079
      java.lang.String v488=java.lang.String.copyValueOf((char[])v59,(int)v335,(int)v248);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764223
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483648
      	at java.lang.String.<init>(String.java:204)
      	at java.lang.String.copyValueOf(String.java:2880)
      YETI EXCEPTION - END**/ 
      /** original locs: 998 minimal locs: 10**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_4() throws Exception {
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      char[] v116=v38.toCharArray(); // time:1316010763856
      java.lang.String v117=new java.lang.String((char[])v116); // time:1316010763856
      java.lang.String v323=v117.concat((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764057
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.concat(String.java:1996)
      YETI EXCEPTION - END**/ 
      /** original locs: 639 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_5() throws Exception {
      java.lang.String v16=new java.lang.String(); // time:1316010763676
      int v28=3; // time:1316010763687
      int v29=-2; // time:1316010763687
      int v30=v16.offsetByCodePoints((int)v28,(int)v29);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763697
      /**YETI EXCEPTION - START 
      java.lang.IndexOutOfBoundsException
      	at java.lang.String.offsetByCodePoints(String.java:800)
      YETI EXCEPTION - END**/ 
      /** original locs: 64 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_6() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      char[] v59=v39.toCharArray(); // time:1316010763725
      float v679=Float.POSITIVE_INFINITY; // time:1316010764464
      java.lang.String v840=java.lang.String.copyValueOf((char[])v59); // time:1316010764677
      java.lang.String v938=java.lang.String.valueOf((float)v679); // time:1316010764843
      java.lang.String v1238=v938.concat((java.lang.String)v840); // time:1316010765559
      int v2471=-6; // time:1316010769122
      java.lang.String[] v2472=v1238.split((java.lang.String)null,(int)v2471);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010769131
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.util.regex.Pattern.<init>(Pattern.java:1132)
      	at java.util.regex.Pattern.compile(Pattern.java:823)
      	at java.lang.String.split(String.java:2292)
      YETI EXCEPTION - END**/ 
      /** original locs: 4863 minimal locs: 13**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_7() throws Exception {
      int v1235=2147483646; // time:1316010765543
      int v1236=8; // time:1316010765543
      java.lang.String v1237=new java.lang.String((byte[])null,(int)v1235,(int)v1236);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010765545
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.checkBounds(String.java:400)
      	at java.lang.String.<init>(String.java:569)
      YETI EXCEPTION - END**/ 
      /** original locs: 2507 minimal locs: 3**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_8() throws Exception {
      int v10=-5; // time:1316010763667
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      int v67=6; // time:1316010763753
      java.lang.CharSequence v68=v38.subSequence((int)v67,(int)v10);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763754
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -11
      	at java.lang.String.substring(String.java:1937)
      	at java.lang.String.subSequence(String.java:1972)
      YETI EXCEPTION - END**/ 
      /** original locs: 157 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_9() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v19=v15.replaceAll((java.lang.String)v18,(java.lang.String)v13); // time:1316010763679
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      java.lang.String v80=java.lang.String.valueOf((float)v8); // time:1316010763762
      java.lang.String v105=new java.lang.String((java.lang.String)v19); // time:1316010763852
      char[] v116=v38.toCharArray(); // time:1316010763856
      java.lang.String v120=java.lang.String.copyValueOf((char[])v116); // time:1316010763857
      java.lang.String v163=v120.replaceAll((java.lang.String)v80,(java.lang.String)v105); // time:1316010763878
      int v184=7; // time:1316010763964
      int v435=v163.lastIndexOf((java.lang.String)null,(int)v184);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764157
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.lastIndexOf(String.java:1823)
      YETI EXCEPTION - END**/ 
      /** original locs: 884 minimal locs: 18**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_10() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      char[] v59=v39.toCharArray(); // time:1316010763725
      int v331=9; // time:1316010764077
      int v443=4; // time:1316010764165
      java.lang.String v444=java.lang.String.valueOf((char[])v59,(int)v443,(int)v331);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764166
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 13
      	at java.lang.String.<init>(String.java:211)
      	at java.lang.String.valueOf(String.java:2865)
      YETI EXCEPTION - END**/ 
      /** original locs: 910 minimal locs: 10**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_11() throws Exception {
      long v0=6L; // time:1316010763662
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v9=java.lang.String.valueOf((float)v8); // time:1316010763667
      java.lang.String v34=java.lang.String.valueOf((long)v0); // time:1316010763710
      java.lang.String v50=v34.intern(); // time:1316010763719
      java.lang.String v58=v9.concat((java.lang.String)v50); // time:1316010763725
      long v510=9L; // time:1316010764236
      java.lang.String v850=java.lang.String.valueOf((long)v510); // time:1316010764703
      java.lang.String v851=v850.replaceAll((java.lang.String)v58,(java.lang.String)v58); // time:1316010764715
      int v1057=v851.indexOf((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010765007
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.indexOf(String.java:1733)
      	at java.lang.String.indexOf(String.java:1715)
      YETI EXCEPTION - END**/ 
      /** original locs: 2150 minimal locs: 10**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_12() throws Exception {
      boolean v518=true; // time:1316010764245
      java.lang.String v519=java.lang.String.valueOf((boolean)v518); // time:1316010764246
      int v975=5; // time:1316010764885
      int v976=v519.indexOf((java.lang.String)null,(int)v975);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764886
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.indexOf(String.java:1733)
      YETI EXCEPTION - END**/ 
      /** original locs: 1992 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_13() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v34=java.lang.String.valueOf((long)v0); // time:1316010763710
      java.lang.String v50=v34.intern(); // time:1316010763719
      int v66=-1; // time:1316010763753
      int v69=-2147483646; // time:1316010763755
      java.lang.String v70=v50.substring((int)v66,(int)v69);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763755
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -1
      	at java.lang.String.substring(String.java:1931)
      YETI EXCEPTION - END**/ 
      /** original locs: 165 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_14() throws Exception {
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      int v44=2147483646; // time:1316010763716
      char[] v116=v38.toCharArray(); // time:1316010763856
      java.lang.String v154=java.lang.String.valueOf((char[])v116); // time:1316010763871
      int v202=2147483647; // time:1316010763969
      byte[] v210=v154.getBytes(); // time:1316010763971
      int v307=0; // time:1316010764036
      java.lang.String v338=new java.lang.String((byte[])v210,(int)v307,(int)v202,(int)v44);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764081
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -3
      	at java.lang.String.checkBounds(String.java:401)
      	at java.lang.String.<init>(String.java:338)
      YETI EXCEPTION - END**/ 
      /** original locs: 681 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_15() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      char[] v116=v38.toCharArray(); // time:1316010763856
      java.lang.String v158=new java.lang.String((byte[])v7); // time:1316010763872
      int v303=0; // time:1316010764034
      int v325=9; // time:1316010764070
      int v378=0; // time:1316010764119
      v158.getChars((int)v378,(int)v303,(char[])v116,(int)v325);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764490
      /**YETI EXCEPTION - START 
      java.lang.ArrayIndexOutOfBoundsException
      	at java.lang.String.getChars(String.java:854)
      YETI EXCEPTION - END**/ 
      /** original locs: 1462 minimal locs: 11**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_16() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v124=new java.lang.String((char[])v2); // time:1316010763858
      char v384='\u0002'; // time:1316010764122
      char v385='\u00ac'; // time:1316010764123
      java.lang.String v386=v124.replace((char)v384,(char)v385); // time:1316010764123
      java.lang.String v1072=v386.trim(); // time:1316010765084
      char[] v1154=v1072.toCharArray(); // time:1316010765247
      int v1418=2147483647; // time:1316010765875
      int v1419=-2; // time:1316010765876
      java.lang.String v1420=java.lang.String.copyValueOf((char[])v1154,(int)v1418,(int)v1419);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010765916
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -2
      	at java.lang.String.<init>(String.java:207)
      	at java.lang.String.copyValueOf(String.java:2880)
      YETI EXCEPTION - END**/ 
      /** original locs: 2832 minimal locs: 12**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_17() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      char[] v59=v39.toCharArray(); // time:1316010763725
      java.lang.String v446=new java.lang.String((char[])v59); // time:1316010764168
      char[] v930=v446.toCharArray(); // time:1316010764817
      int v1452=1; // time:1316010766029
      java.lang.String v1578=java.lang.String.valueOf((char[])v930); // time:1316010766383
      int v1670=7; // time:1316010766590
      int v1671=v1578.offsetByCodePoints((int)v1452,(int)v1670);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010766593
      /**YETI EXCEPTION - START 
      java.lang.IndexOutOfBoundsException
      	at java.lang.Character.offsetByCodePointsImpl(Character.java:2794)
      	at java.lang.String.offsetByCodePoints(String.java:802)
      YETI EXCEPTION - END**/ 
      /** original locs: 3294 minimal locs: 13**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_18() throws Exception {
      int v66=-1; // time:1316010763753
      char v94='\n'; // time:1316010763796
      java.lang.String v145=java.lang.String.valueOf((char)v94); // time:1316010763867
      char[] v155=v145.toCharArray(); // time:1316010763871
      int v312=2147483646; // time:1316010764045
      java.lang.String v313=java.lang.String.valueOf((char[])v155,(int)v66,(int)v312);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764045
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -1
      	at java.lang.String.<init>(String.java:204)
      	at java.lang.String.valueOf(String.java:2865)
      YETI EXCEPTION - END**/ 
      /** original locs: 606 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_19() throws Exception {
      float v179=Float.POSITIVE_INFINITY; // time:1316010763961
      java.lang.String v180=java.lang.String.valueOf((float)v179); // time:1316010763961
      java.lang.String v1499=v180.toUpperCase(); // time:1316010766154
      java.lang.String v1986=java.lang.String.valueOf((java.lang.String)v1499); // time:1316010767331
      int v2197=0; // time:1316010767885
      int v2198=-7; // time:1316010767888
      int v2199=v1986.offsetByCodePoints((int)v2197,(int)v2198);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010767891
      /**YETI EXCEPTION - START 
      java.lang.IndexOutOfBoundsException
      	at java.lang.Character.offsetByCodePointsImpl(Character.java:2806)
      	at java.lang.String.offsetByCodePoints(String.java:802)
      YETI EXCEPTION - END**/ 
      /** original locs: 4362 minimal locs: 7**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_20() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      int v22=7; // time:1316010763682
      int v28=3; // time:1316010763687
      int v60=0; // time:1316010763725
      v6.getBytes((int)v28,(int)v22,(byte[])null,(int)v60);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763726
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 7
      	at java.lang.String.getBytes(String.java:907)
      YETI EXCEPTION - END**/ 
      /** original locs: 139 minimal locs: 7**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_21() throws Exception {
      double v217=Double.POSITIVE_INFINITY; // time:1316010763975
      java.lang.String v546=java.lang.String.valueOf((double)v217); // time:1316010764276
      boolean v1144=v546.startsWith((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010765232
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.startsWith(String.java:1421)
      	at java.lang.String.startsWith(String.java:1450)
      YETI EXCEPTION - END**/ 
      /** original locs: 2316 minimal locs: 3**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_22() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v14=v13.trim(); // time:1316010763676
      byte[] v808=v14.getBytes(); // time:1316010764638
      java.lang.String v1070=new java.lang.String((byte[])v808,(java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010765051
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException: charsetName
      	at java.lang.String.<init>(String.java:441)
      	at java.lang.String.<init>(String.java:515)
      YETI EXCEPTION - END**/ 
      /** original locs: 2185 minimal locs: 7**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_23() throws Exception {
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v9=java.lang.String.valueOf((float)v8); // time:1316010763667
      int v26=-5; // time:1316010763685
      byte[] v147=v9.getBytes(); // time:1316010763867
      java.lang.String v250=new java.lang.String(); // time:1316010763992
      java.lang.String v434=v250.intern(); // time:1316010764156
      java.lang.String v526=new java.lang.String((java.lang.String)v434); // time:1316010764251
      int v553=6; // time:1316010764280
      java.lang.String v554=new java.lang.String((byte[])v147,(int)v26,(int)v553,(java.lang.String)v526);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764281
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -5
      	at java.lang.String.checkBounds(String.java:399)
      	at java.lang.String.<init>(String.java:442)
      YETI EXCEPTION - END**/ 
      /** original locs: 1137 minimal locs: 9**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_24() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v80=java.lang.String.valueOf((float)v8); // time:1316010763762
      java.lang.String v81=new java.lang.String((java.lang.String)v80); // time:1316010763763
      java.lang.String v135=v81.replaceFirst((java.lang.String)null,(java.lang.String)v6);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763863
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.util.regex.Pattern.<init>(Pattern.java:1132)
      	at java.util.regex.Pattern.compile(Pattern.java:823)
      	at java.lang.String.replaceFirst(String.java:2146)
      YETI EXCEPTION - END**/ 
      /** original locs: 294 minimal locs: 7**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_25() throws Exception {
      int v11=3; // time:1316010763667
      java.lang.String v16=new java.lang.String(); // time:1316010763676
      int v20=v16.codePointBefore((int)v11);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763681
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 3
      	at java.lang.String.codePointBefore(String.java:745)
      YETI EXCEPTION - END**/ 
      /** original locs: 38 minimal locs: 3**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_26() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v158=new java.lang.String((byte[])v7); // time:1316010763872
      boolean v299=v158.contains((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764033
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.contains(String.java:2103)
      YETI EXCEPTION - END**/ 
      /** original locs: 576 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_27() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      java.lang.String v16=new java.lang.String(); // time:1316010763676
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v47=v18.replaceAll((java.lang.String)v6,(java.lang.String)v16); // time:1316010763718
      boolean v101=v47.matches((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763798
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.util.regex.Pattern.<init>(Pattern.java:1132)
      	at java.util.regex.Pattern.compile(Pattern.java:823)
      	at java.util.regex.Pattern.matches(Pattern.java:928)
      	at java.lang.String.matches(String.java:2090)
      YETI EXCEPTION - END**/ 
      /** original locs: 234 minimal locs: 7**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_28() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v34=java.lang.String.valueOf((long)v0); // time:1316010763710
      java.lang.String v50=v34.intern(); // time:1316010763719
      boolean v108=v50.endsWith((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763853
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.endsWith(String.java:1465)
      YETI EXCEPTION - END**/ 
      /** original locs: 250 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_29() throws Exception {
      int v1729=0; // time:1316010766713
      int v1818=4; // time:1316010766920
      java.lang.String v1819=new java.lang.String((char[])null,(int)v1818,(int)v1729);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010766922
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.<init>(String.java:210)
      YETI EXCEPTION - END**/ 
      /** original locs: 3585 minimal locs: 3**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_30() throws Exception {
      java.lang.String v318=new java.lang.String((char[])null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764051
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.<init>(String.java:177)
      YETI EXCEPTION - END**/ 
      /** original locs: 624 minimal locs: 1**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_31() throws Exception {
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      char[] v116=v38.toCharArray(); // time:1316010763856
      java.lang.String v154=java.lang.String.valueOf((char[])v116); // time:1316010763871
      byte[] v210=v154.getBytes(); // time:1316010763971
      java.lang.String v288=new java.lang.String((byte[])v210); // time:1316010764018
      int v308=3; // time:1316010764036
      int v523=0; // time:1316010764249
      java.lang.CharSequence v524=v288.subSequence((int)v523,(int)v308);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764250
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 3
      	at java.lang.String.substring(String.java:1934)
      	at java.lang.String.subSequence(String.java:1972)
      YETI EXCEPTION - END**/ 
      /** original locs: 1072 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_32() throws Exception {
      java.lang.String v584=new java.lang.String(); // time:1316010764321
      int v829=2147483647; // time:1316010764660
      int v901=2; // time:1316010764779
      java.lang.String v1090=v584.substring((int)v829,(int)v901);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010765114
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 2
      	at java.lang.String.substring(String.java:1934)
      YETI EXCEPTION - END**/ 
      /** original locs: 2222 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_33() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v17=v15.replaceFirst((java.lang.String)v13,(java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763677
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException: replacement
      	at java.util.regex.Matcher.replaceFirst(Matcher.java:857)
      	at java.lang.String.replaceFirst(String.java:2146)
      YETI EXCEPTION - END**/ 
      /** original locs: 29 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_34() throws Exception {
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v80=java.lang.String.valueOf((float)v8); // time:1316010763762
      int v139=-10; // time:1316010763864
      java.lang.String v146=v80.toLowerCase(); // time:1316010763867
      int v493=-1; // time:1316010764226
      int v494=7; // time:1316010764226
      boolean v495=v146.regionMatches((int)v493,(java.lang.String)null,(int)v494,(int)v139);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764227
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.regionMatches(String.java:1296)
      YETI EXCEPTION - END**/ 
      /** original locs: 1011 minimal locs: 7**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_35() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      int v22=7; // time:1316010763682
      int v26=-5; // time:1316010763685
      java.lang.String v27=new java.lang.String((byte[])v7,(int)v22,(int)v26,(java.lang.String)v13);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763686
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -5
      	at java.lang.String.checkBounds(String.java:397)
      	at java.lang.String.<init>(String.java:442)
      YETI EXCEPTION - END**/ 
      /** original locs: 55 minimal locs: 9**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_36() throws Exception {
      java.lang.String v657=java.lang.String.copyValueOf((char[])null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764442
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.copyValueOf(String.java:2892)
      YETI EXCEPTION - END**/ 
      /** original locs: 1383 minimal locs: 1**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_37() throws Exception {
      int v1435=-10; // time:1316010765992
      java.lang.String v1436=new java.lang.String((byte[])null,(int)v1435);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010765995
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.<init>(String.java:388)
      YETI EXCEPTION - END**/ 
      /** original locs: 2866 minimal locs: 2**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_38() throws Exception {
      double v217=Double.POSITIVE_INFINITY; // time:1316010763975
      boolean v637=false; // time:1316010764414
      java.lang.String v945=java.lang.String.valueOf((double)v217); // time:1316010764853
      java.lang.String v946=java.lang.String.valueOf((java.lang.String)v945); // time:1316010764854
      int v1231=2147483647; // time:1316010765535
      int v1715=2147483646; // time:1316010766688
      int v1891=4; // time:1316010767091
      boolean v1892=v946.regionMatches((boolean)v637,(int)v1715,(java.lang.String)null,(int)v1231,(int)v1891);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010767093
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.regionMatches(String.java:1365)
      YETI EXCEPTION - END**/ 
      /** original locs: 3730 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_39() throws Exception {
      long v0=6L; // time:1316010763662
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v9=java.lang.String.valueOf((float)v8); // time:1316010763667
      java.lang.String v34=java.lang.String.valueOf((long)v0); // time:1316010763710
      java.lang.String v50=v34.intern(); // time:1316010763719
      java.lang.String v58=v9.concat((java.lang.String)v50); // time:1316010763725
      char v94='\n'; // time:1316010763796
      java.lang.String v95=v58.replace((char)v94,(char)v94); // time:1316010763796
      boolean v110=false; // time:1316010763854
      java.lang.String v137=java.lang.String.valueOf((java.lang.String)v95); // time:1316010763864
      java.lang.String v150=java.lang.String.valueOf((boolean)v110); // time:1316010763870
      long v240=2147483646L; // time:1316010763989
      java.lang.String v241=java.lang.String.valueOf((long)v240); // time:1316010763989
      java.lang.String v243=new java.lang.String((java.lang.String)v137); // time:1316010763990
      java.lang.String v309=java.lang.String.valueOf((float)v8); // time:1316010764044
      java.lang.String v310=v309.concat((java.lang.String)v243); // time:1316010764044
      java.lang.String v348=v310.replaceFirst((java.lang.String)v241,(java.lang.String)v243); // time:1316010764086
      int v381=-1; // time:1316010764120
      java.lang.String v563=v150.toString(); // time:1316010764296
      int v613=-2147483648; // time:1316010764357
      byte[] v617=v348.getBytes(); // time:1316010764360
      int v652=5; // time:1316010764432
      v563.getBytes((int)v652,(int)v613,(byte[])v617,(int)v381);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764437
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 2147483643
      	at java.lang.String.getBytes(String.java:910)
      YETI EXCEPTION - END**/ 
      /** original locs: 1372 minimal locs: 23**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_40() throws Exception {
      boolean v387=false; // time:1316010764123
      java.lang.String v388=java.lang.String.valueOf((boolean)v387); // time:1316010764123
      int v998=-7; // time:1316010764913
      boolean v999=v388.startsWith((java.lang.String)null,(int)v998);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764916
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.startsWith(String.java:1421)
      YETI EXCEPTION - END**/ 
      /** original locs: 2032 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_41() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      int v3=-2147483647; // time:1316010763663
      int v4=0; // time:1316010763663
      java.lang.String v5=new java.lang.String((char[])v2,(int)v3,(int)v4);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763665
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483647
      	at java.lang.String.<init>(String.java:204)
      YETI EXCEPTION - END**/ 
      /** original locs: 6 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_42() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      int v3=-2147483647; // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      int v32=0; // time:1316010763708
      int v33=v15.codePointCount((int)v3,(int)v32);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763709
      /**YETI EXCEPTION - START 
      java.lang.IndexOutOfBoundsException
      	at java.lang.String.codePointCount(String.java:773)
      YETI EXCEPTION - END**/ 
      /** original locs: 72 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_43() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v9=java.lang.String.valueOf((float)v8); // time:1316010763667
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v34=java.lang.String.valueOf((long)v0); // time:1316010763710
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      java.lang.String v50=v34.intern(); // time:1316010763719
      java.lang.String v58=v9.concat((java.lang.String)v50); // time:1316010763725
      char[] v59=v39.toCharArray(); // time:1316010763725
      char v94='\n'; // time:1316010763796
      java.lang.String v95=v58.replace((char)v94,(char)v94); // time:1316010763796
      java.lang.String v137=java.lang.String.valueOf((java.lang.String)v95); // time:1316010763864
      long v240=2147483646L; // time:1316010763989
      java.lang.String v241=java.lang.String.valueOf((long)v240); // time:1316010763989
      java.lang.String v243=new java.lang.String((java.lang.String)v137); // time:1316010763990
      int v279=2; // time:1316010764003
      java.lang.String v309=java.lang.String.valueOf((float)v8); // time:1316010764044
      java.lang.String v310=v309.concat((java.lang.String)v243); // time:1316010764044
      java.lang.String v348=v310.replaceFirst((java.lang.String)v241,(java.lang.String)v243); // time:1316010764086
      byte[] v617=v348.getBytes(); // time:1316010764360
      int v618=10; // time:1316010764361
      java.lang.String v619=new java.lang.String((byte[])v617,(int)v618); // time:1316010764361
      int v625=7; // time:1316010764368
      int v626=-1; // time:1316010764369
      v619.getChars((int)v625,(int)v626,(char[])v59,(int)v279);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764370
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -8
      	at java.lang.String.getChars(String.java:852)
      YETI EXCEPTION - END**/ 
      /** original locs: 1308 minimal locs: 28**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_44() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v19=v15.replaceAll((java.lang.String)v18,(java.lang.String)v13); // time:1316010763679
      java.lang.String v31=new java.lang.String((java.lang.String)v19); // time:1316010763708
      java.lang.String v133=v31.toString(); // time:1316010763861
      java.lang.String v134=v133.toString(); // time:1316010763862
      java.lang.String v219=v134.toString(); // time:1316010763976
      int v1937=-2; // time:1316010767211
      byte[] v2107=v219.getBytes(); // time:1316010767650
      int v2156=2147483645; // time:1316010767751
      java.lang.String v2157=new java.lang.String((byte[])v2107,(int)v1937,(int)v2156,(java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010767755
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException: charsetName
      	at java.lang.String.<init>(String.java:441)
      YETI EXCEPTION - END**/ 
      /** original locs: 4275 minimal locs: 17**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_45() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v19=v15.replaceAll((java.lang.String)v18,(java.lang.String)v13); // time:1316010763679
      java.lang.String v31=new java.lang.String((java.lang.String)v19); // time:1316010763708
      byte[] v63=v31.getBytes((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763751
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.getBytes(String.java:945)
      YETI EXCEPTION - END**/ 
      /** original locs: 147 minimal locs: 11**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_46() throws Exception {
      java.lang.String v620=java.lang.String.valueOf((char[])null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764363
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.<init>(String.java:177)
      	at java.lang.String.valueOf(String.java:2840)
      YETI EXCEPTION - END**/ 
      /** original locs: 1289 minimal locs: 1**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_47() throws Exception {
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v80=java.lang.String.valueOf((float)v8); // time:1316010763762
      java.lang.String v146=v80.toLowerCase(); // time:1316010763867
      boolean v904=v146.contentEquals((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764782
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.contentEquals(String.java:1061)
      YETI EXCEPTION - END**/ 
      /** original locs: 1848 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_48() throws Exception {
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      int v65=-2147483648; // time:1316010763753
      char[] v116=v38.toCharArray(); // time:1316010763856
      int v358=2147483646; // time:1316010764092
      java.lang.String v359=java.lang.String.valueOf((char[])v116,(int)v358,(int)v65);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764093
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483648
      	at java.lang.String.<init>(String.java:207)
      	at java.lang.String.valueOf(String.java:2865)
      YETI EXCEPTION - END**/ 
      /** original locs: 720 minimal locs: 5**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_49() throws Exception {
      int v4=0; // time:1316010763663
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v9=java.lang.String.valueOf((float)v8); // time:1316010763667
      int v69=-2147483646; // time:1316010763755
      byte[] v147=v9.getBytes(); // time:1316010763867
      java.lang.String v529=new java.lang.String((byte[])v147,(int)v69,(int)v4);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764253
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483646
      	at java.lang.String.checkBounds(String.java:399)
      	at java.lang.String.<init>(String.java:569)
      YETI EXCEPTION - END**/ 
      /** original locs: 1083 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_50() throws Exception {
      int v90=10; // time:1316010763794
      char v94='\n'; // time:1316010763796
      java.lang.String v145=java.lang.String.valueOf((char)v94); // time:1316010763867
      char[] v155=v145.toCharArray(); // time:1316010763871
      int v327=7; // time:1316010764072
      java.lang.String v328=new java.lang.String((char[])v155,(int)v90,(int)v327);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764075
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 17
      	at java.lang.String.<init>(String.java:211)
      YETI EXCEPTION - END**/ 
      /** original locs: 655 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_51() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      int v144=1; // time:1316010763866
      int v364=2147483646; // time:1316010764100
      java.lang.String v365=java.lang.String.copyValueOf((char[])v2,(int)v364,(int)v144);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764100
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 2147483647
      	at java.lang.String.<init>(String.java:211)
      	at java.lang.String.copyValueOf(String.java:2880)
      YETI EXCEPTION - END**/ 
      /** original locs: 737 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_52() throws Exception {
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      char[] v116=v38.toCharArray(); // time:1316010763856
      java.lang.String v154=java.lang.String.valueOf((char[])v116); // time:1316010763871
      java.lang.String v250=new java.lang.String(); // time:1316010763992
      java.lang.String v2129=v250.toLowerCase(); // time:1316010767703
      java.lang.String v2390=v154.replaceAll((java.lang.String)v2129,(java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010768611
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.util.regex.Matcher.appendReplacement(Matcher.java:699)
      	at java.util.regex.Matcher.replaceAll(Matcher.java:813)
      	at java.lang.String.replaceAll(String.java:2189)
      YETI EXCEPTION - END**/ 
      /** original locs: 4710 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_53() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      char[] v59=v39.toCharArray(); // time:1316010763725
      boolean v413=false; // time:1316010764142
      java.lang.String v414=java.lang.String.valueOf((boolean)v413); // time:1316010764142
      java.lang.String v446=new java.lang.String((char[])v59); // time:1316010764168
      java.lang.String v799=v414.replaceAll((java.lang.String)null,(java.lang.String)v446);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764627
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.util.regex.Pattern.<init>(Pattern.java:1132)
      	at java.util.regex.Pattern.compile(Pattern.java:823)
      	at java.lang.String.replaceAll(String.java:2189)
      YETI EXCEPTION - END**/ 
      /** original locs: 1668 minimal locs: 11**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_54() throws Exception {
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v9=java.lang.String.valueOf((float)v8); // time:1316010763667
      int v96=1761908439; // time:1316010763796
      byte[] v147=v9.getBytes(); // time:1316010763867
      int v197=2147483645; // time:1316010763966
      java.lang.String v198=new java.lang.String((byte[])v147,(int)v96,(int)v197);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763967
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -385575212
      	at java.lang.String.checkBounds(String.java:401)
      	at java.lang.String.<init>(String.java:569)
      YETI EXCEPTION - END**/ 
      /** original locs: 409 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_55() throws Exception {
      java.lang.String v1558=new java.lang.String(); // time:1316010766328
      int v1725=v1558.lastIndexOf((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010766702
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.lastIndexOf(String.java:1823)
      	at java.lang.String.lastIndexOf(String.java:1805)
      YETI EXCEPTION - END**/ 
      /** original locs: 3390 minimal locs: 2**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_56() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v14=v13.trim(); // time:1316010763676
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v16=new java.lang.String(); // time:1316010763676
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v19=v15.replaceAll((java.lang.String)v18,(java.lang.String)v13); // time:1316010763679
      java.lang.String v31=new java.lang.String((java.lang.String)v19); // time:1316010763708
      java.lang.String v47=v18.replaceAll((java.lang.String)v6,(java.lang.String)v16); // time:1316010763718
      java.lang.String v61=v47.replace((java.lang.String)v14,(java.lang.String)v14); // time:1316010763739
      java.lang.String v62=v16.concat((java.lang.String)v31); // time:1316010763739
      int v139=-10; // time:1316010763864
      java.lang.String v182=v14.replace((java.lang.String)v62,(java.lang.String)v61); // time:1316010763964
      int v224=2147483646; // time:1316010763977
      java.lang.String v225=v182.substring((int)v224,(int)v139);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763978
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 2147483640
      	at java.lang.String.substring(String.java:1937)
      YETI EXCEPTION - END**/ 
      /** original locs: 447 minimal locs: 19**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_57() throws Exception {
      long v0=6L; // time:1316010763662
      int v22=7; // time:1316010763682
      java.lang.String v148=java.lang.String.valueOf((long)v0); // time:1316010763868
      java.lang.String v149=v148.substring((int)v22);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763869
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -6
      	at java.lang.String.substring(String.java:1937)
      	at java.lang.String.substring(String.java:1904)
      YETI EXCEPTION - END**/ 
      /** original locs: 326 minimal locs: 4**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_58() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      int v10=-5; // time:1316010763667
      int v11=3; // time:1316010763667
      java.lang.CharSequence v12=v1.subSequence((int)v10,(int)v11);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763668
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -5
      	at java.lang.String.substring(String.java:1931)
      	at java.lang.String.subSequence(String.java:1972)
      YETI EXCEPTION - END**/ 
      /** original locs: 18 minimal locs: 5**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_59() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      int v44=2147483646; // time:1316010763716
      int v77=-1; // time:1316010763760
      java.lang.String v226=new java.lang.String((byte[])v7,(int)v44,(int)v77);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763980
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -1
      	at java.lang.String.checkBounds(String.java:397)
      	at java.lang.String.<init>(String.java:569)
      YETI EXCEPTION - END**/ 
      /** original locs: 453 minimal locs: 7**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_60() throws Exception {
      char v282='\u00ab'; // time:1316010764004
      java.lang.String v283=java.lang.String.valueOf((char)v282); // time:1316010764004
      java.lang.String[] v284=v283.split((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764012
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.util.regex.Pattern.<init>(Pattern.java:1132)
      	at java.util.regex.Pattern.compile(Pattern.java:823)
      	at java.lang.String.split(String.java:2292)
      	at java.lang.String.split(String.java:2334)
      YETI EXCEPTION - END**/ 
      /** original locs: 543 minimal locs: 3**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_61() throws Exception {
      char v94='\n'; // time:1316010763796
      java.lang.String v145=java.lang.String.valueOf((char)v94); // time:1316010763867
      char[] v155=v145.toCharArray(); // time:1316010763871
      int v204=2147483647; // time:1316010763969
      int v205=-2; // time:1316010763969
      java.lang.String v206=new java.lang.String((char[])v155,(int)v204,(int)v205);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763970
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -2
      	at java.lang.String.<init>(String.java:207)
      YETI EXCEPTION - END**/ 
      /** original locs: 423 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_62() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v19=v15.replaceAll((java.lang.String)v18,(java.lang.String)v13); // time:1316010763679
      java.lang.String v31=new java.lang.String((java.lang.String)v19); // time:1316010763708
      java.lang.String v54=new java.lang.String((byte[])null,(java.lang.String)v31);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763722
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.<init>(String.java:515)
      YETI EXCEPTION - END**/ 
      /** original locs: 121 minimal locs: 11**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_63() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v261=new java.lang.String((char[])v2); // time:1316010763999
      int v265=-8; // time:1316010764000
      java.lang.String v266=v261.substring((int)v265);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764000
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -8
      	at java.lang.String.substring(String.java:1931)
      	at java.lang.String.substring(String.java:1904)
      YETI EXCEPTION - END**/ 
      /** original locs: 519 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_64() throws Exception {
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      char[] v116=v38.toCharArray(); // time:1316010763856
      java.lang.String v154=java.lang.String.valueOf((char[])v116); // time:1316010763871
      byte[] v210=v154.getBytes(); // time:1316010763971
      int v317=-1; // time:1316010764050
      int v324=-4; // time:1316010764070
      int v325=9; // time:1316010764070
      java.lang.String v326=new java.lang.String((byte[])v210,(int)v324,(int)v317,(int)v325);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764071
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -1
      	at java.lang.String.checkBounds(String.java:399)
      	at java.lang.String.<init>(String.java:338)
      YETI EXCEPTION - END**/ 
      /** original locs: 647 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_65() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v107=java.lang.String.valueOf((java.lang.String)v18); // time:1316010763852
      java.lang.String v148=java.lang.String.valueOf((long)v0); // time:1316010763868
      char v836='\u0002'; // time:1316010764670
      char v837='\u00ad'; // time:1316010764671
      java.lang.String v838=v107.replace((char)v836,(char)v837); // time:1316010764676
      int v922=4; // time:1316010764812
      java.lang.String v923=java.lang.String.valueOf((int)v922); // time:1316010764813
      java.lang.String v943=v923.replace((java.lang.String)v148,(java.lang.String)v838); // time:1316010764850
      int v1193=v943.compareToIgnoreCase((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010765374
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String$CaseInsensitiveComparator.compare(String.java:1217)
      	at java.lang.String$CaseInsensitiveComparator.compare(String.java:1211)
      	at java.lang.String.compareToIgnoreCase(String.java:1258)
      YETI EXCEPTION - END**/ 
      /** original locs: 2406 minimal locs: 13**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_66() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v71=new java.lang.String((java.lang.String)v15); // time:1316010763756
      java.lang.String v148=java.lang.String.valueOf((long)v0); // time:1316010763868
      java.lang.String v168=v71.replace((java.lang.String)null,(java.lang.String)v148);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763910
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.replace(String.java:2207)
      YETI EXCEPTION - END**/ 
      /** original locs: 367 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_67() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      int v22=7; // time:1316010763682
      int v23=v18.codePointAt((int)v22);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763683
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 7
      	at java.lang.String.codePointAt(String.java:715)
      YETI EXCEPTION - END**/ 
      /** original locs: 46 minimal locs: 6**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_68() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v19=v15.replaceAll((java.lang.String)v18,(java.lang.String)v13); // time:1316010763679
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      char[] v59=v39.toCharArray(); // time:1316010763725
      java.lang.String v105=new java.lang.String((java.lang.String)v19); // time:1316010763852
      int v306=-10; // time:1316010764036
      int v307=0; // time:1316010764036
      int v308=3; // time:1316010764036
      v105.getChars((int)v306,(int)v307,(char[])v59,(int)v308);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764037
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -10
      	at java.lang.String.getChars(String.java:846)
      YETI EXCEPTION - END**/ 
      /** original locs: 596 minimal locs: 16**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_69() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      java.lang.String v15=new java.lang.String((byte[])v7); // time:1316010763676
      java.lang.String v39=v15.toLowerCase(); // time:1316010763713
      int v90=10; // time:1316010763794
      int v91=6; // time:1316010763794
      java.lang.String v92=new java.lang.String((byte[])v7,(int)v90,(int)v91,(java.lang.String)v39);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763795
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: 16
      	at java.lang.String.checkBounds(String.java:401)
      	at java.lang.String.<init>(String.java:442)
      YETI EXCEPTION - END**/ 
      /** original locs: 213 minimal locs: 9**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_70() throws Exception {
      java.lang.String v1437=new java.lang.String(); // time:1316010765997
      int v1575=v1437.compareTo((java.lang.String)null);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010766377
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.compareTo(String.java:1167)
      YETI EXCEPTION - END**/ 
      /** original locs: 3132 minimal locs: 2**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_71() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      char[] v2=v1.toCharArray(); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      java.lang.String v13=java.lang.String.copyValueOf((char[])v2); // time:1316010763675
      java.lang.String v16=new java.lang.String(); // time:1316010763676
      java.lang.String v18=v6.toUpperCase(); // time:1316010763679
      java.lang.String v34=java.lang.String.valueOf((long)v0); // time:1316010763710
      java.lang.String v47=v18.replaceAll((java.lang.String)v6,(java.lang.String)v16); // time:1316010763718
      java.lang.String v50=v34.intern(); // time:1316010763719
      java.lang.String v89=v50.replaceFirst((java.lang.String)v47,(java.lang.String)v13); // time:1316010763794
      java.lang.String v100=v89.toUpperCase(); // time:1316010763798
      int v103=-1; // time:1316010763812
      java.lang.String v238=v100.toLowerCase(); // time:1316010763989
      char v282='\u00ab'; // time:1316010764004
      char v294='\u0001'; // time:1316010764029
      java.lang.String v295=v238.replace((char)v282,(char)v294); // time:1316010764029
      char v363=v295.charAt((int)v103);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764096
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -1
      	at java.lang.String.charAt(String.java:686)
      YETI EXCEPTION - END**/ 
      /** original locs: 730 minimal locs: 18**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_72() throws Exception {
      long v0=6L; // time:1316010763662
      float v8=1.4E-45f; // time:1316010763666
      java.lang.String v9=java.lang.String.valueOf((float)v8); // time:1316010763667
      java.lang.String v34=java.lang.String.valueOf((long)v0); // time:1316010763710
      java.lang.String v38=new java.lang.String(); // time:1316010763713
      java.lang.String v50=v34.intern(); // time:1316010763719
      java.lang.String v58=v9.concat((java.lang.String)v50); // time:1316010763725
      int v65=-2147483648; // time:1316010763753
      char v94='\n'; // time:1316010763796
      java.lang.String v95=v58.replace((char)v94,(char)v94); // time:1316010763796
      char[] v116=v38.toCharArray(); // time:1316010763856
      java.lang.String v137=java.lang.String.valueOf((java.lang.String)v95); // time:1316010763864
      java.lang.String v154=java.lang.String.valueOf((char[])v116); // time:1316010763871
      byte[] v210=v154.getBytes(); // time:1316010763971
      int v248=3; // time:1316010763992
      int v436=-8; // time:1316010764158
      v137.getBytes((int)v65,(int)v248,(byte[])v210,(int)v436);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010764159
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -2147483648
      	at java.lang.String.getBytes(String.java:904)
      YETI EXCEPTION - END**/ 
      /** original locs: 891 minimal locs: 17**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_73() throws Exception {
      long v0=6L; // time:1316010763662
      java.lang.String v1=java.lang.String.valueOf((long)v0); // time:1316010763663
      java.lang.String v6=v1.intern(); // time:1316010763666
      byte[] v7=v6.getBytes(); // time:1316010763666
      int v26=-5; // time:1316010763685
      int v55=0; // time:1316010763723
      int v56=0; // time:1316010763723
      java.lang.String v57=new java.lang.String((byte[])v7,(int)v55,(int)v56,(int)v26);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763724
      /**YETI EXCEPTION - START 
      java.lang.StringIndexOutOfBoundsException: String index out of range: -5
      	at java.lang.String.checkBounds(String.java:397)
      	at java.lang.String.<init>(String.java:338)
      YETI EXCEPTION - END**/ 
      /** original locs: 129 minimal locs: 8**/
   
   }


   /** Test case automatically generated by YETI **/
   @YetiTrace public void test_74() throws Exception {
      int v86=2147483645; // time:1316010763789
      int v87=10; // time:1316010763789
      java.lang.String v88=java.lang.String.copyValueOf((char[])null,(int)v86,(int)v87);
      /**BUG FOUND: RUNTIME EXCEPTION**/ // time:1316010763793
      /**YETI EXCEPTION - START 
      java.lang.NullPointerException
      	at java.lang.String.<init>(String.java:210)
      	at java.lang.String.copyValueOf(String.java:2880)
      YETI EXCEPTION - END**/ 
      /** original locs: 203 minimal locs: 3**/
   
   }


/** Non-Unique bugs: 431, Unique Bugs: 74, Logs size (locs): 4995**/

}